apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-redis-exporter
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.exporters.redis.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "harbor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis-exporter