apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
  namespace: harborend
data:
  config.yml: |
    # Core configuration
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
    storage:
      type: ebs
      ebs:
        storageClass: ebs-sc
