apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor.fullname" . }}-core-config
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
data:
  config.yml: |
    # Core configuration
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
    storage:
      type: ebs
      ebs:
        storageClass: ebs-sc