apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "harbor.fullname" . }}-core-pdb
spec:
  minAvailable: {{ .Values.core.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "harbor.selectorLabels" . | nindent 6 }}
      component: core