apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-core
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "harbor.selectorLabels" . | nindent 4 }}
    component: core