apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-redis
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 6379
    name: redis
  selector:
    {{- include "harbor.selectorLabels" . | nindent 4 }}
    component: redis