apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor.fullname" . }}-postgresql-config
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE DATABASE registry;
    CREATE DATABASE notary_server;
    CREATE DATABASE notary_signer;
    
    \c registry;
    CREATE TABLE IF NOT EXISTS schema_migrations (
        version bigint NOT NULL PRIMARY KEY,
        dirty boolean NOT NULL
    );
    
    \c notary_server;
    CREATE TABLE IF NOT EXISTS schema_migrations (
        version bigint NOT NULL PRIMARY KEY,
        dirty boolean NOT NULL
    );
    
    \c notary_signer;
    CREATE TABLE IF NOT EXISTS schema_migrations (
        version bigint NOT NULL PRIMARY KEY,
        dirty boolean NOT NULL
    );