{{- if and .Values.postgresql.persistence.enabled (not .Values.postgresql.statefulset.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harbor.fullname" . }}-postgresql-pvc
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | default "efs-sc" }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | default "8Gi" }}
{{- end }}