apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-postgresql
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  selector:
    {{- include "harbor.selectorLabels" . | nindent 4 }}
    component: postgresql