apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor.fullname" . }}-portal-config
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
data:
  config.yaml: |
    # Portal configuration
    api:
      baseUrl: http://{{ include "harbor.fullname" . }}-core:{{ .Values.core.service.port }}
      baseUrlInEnv: false
    # UI settings
    ui:
      logo: ""
      logoWidth: "41px"
      showSelfRegistration: {{ .Values.portal.showSelfRegistration | default false }}
      harborVersion: {{ .Values.portal.harborVersion | default "v2.8.0" }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor.fullname" . }}-portal-nginx-config
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes auto;
    events {
      worker_connections 1024;
    }
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      sendfile on;
      keepalive_timeout 65;
      server {
        listen 8080;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        location / {
          try_files $uri $uri/ /index.html;
        }
        location /api/ {
          proxy_pass http://{{ include "harbor.fullname" . }}-core:{{ .Values.core.service.port }}/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
          root /usr/share/nginx/html;
        }
      }
    }