apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor.fullname" . }}-portal
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      {{- include "harbor.selectorLabels" . | nindent 6 }}
      component: portal
  template:
    metadata:
      labels:
        {{- include "harbor.selectorLabels" . | nindent 8 }}
        component: portal
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: portal
        image: "{{ .Values.portal.image.repository }}:{{ .Values.portal.image.tag }}"
        imagePullPolicy: {{ .Values.portal.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: CORE_URL
          value: http://{{ include "harbor.fullname" . }}-core:{{ .Values.core.service.port }}
        - name: NODE_ENV
          value: {{ .Values.portal.nodeEnv | default "production" }}
        volumeMounts:
        - name: config
          mountPath: /etc/portal/config.yaml
          subPath: config.yaml
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          {{- toYaml .Values.portal.resources | nindent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "harbor.fullname" . }}-portal-config
      - name: nginx-config
        configMap:
          name: {{ include "harbor.fullname" . }}-portal-nginx-config