apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.fullname" . }}-portal
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.portal.service.type }}
  ports:
    - port: {{ .Values.portal.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "harbor.selectorLabels" . | nindent 4 }}
    component: portal