{{- if .Values.trivy.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harbor.fullname" . }}-trivy-pvc
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: trivy
spec:
  accessModes:
    - {{ .Values.trivy.persistence.accessMode | default "ReadWriteMany" }}
  storageClassName: {{ .Values.persistence.storageClass | default "efs-sc" }}
  resources:
    requests:
      storage: {{ .Values.trivy.persistence.size | default "5Gi" }}
{{- end }}