apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-core-secrets
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.core.secretKey | default (randAlphaNum 16 | b64enc) | b64enc | quote }}
  CORE_SECRET: {{ .Values.core.coreSecret | default (randAlphaNum 16 | b64enc) | b64enc | quote }}
  REGISTRY_HTTP_SECRET: {{ .Values.core.registryHttpSecret | default (randAlphaNum 16 | b64enc) | b64enc | quote }}