apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-jobservice-secrets
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  JOBSERVICE_SECRET: {{ .Values.secrets.jobservice.secretKey | b64enc | default (randAlphaNum 32 | b64enc) }}
  CORE_SECRET: {{ .Values.secrets.core.secretKey | b64enc }}
  DATABASE_PASSWORD: {{ .Values.secrets.core.databasePassword | b64enc }}
  # Registry storage credentials for EBS
  REGISTRY_STORAGE_S3_ACCESSKEY: {{ .Values.secrets.ebs.accessKey | b64enc }}
  REGISTRY_STORAGE_S3_SECRETKEY: {{ .Values.secrets.ebs.secretKey | b64enc }}