apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-postgresql-secrets
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresql.password | b64enc | default (randAlphaNum 16 | b64enc) }}
  POSTGRES_USER: {{ .Values.secrets.postgresql.user | default "postgres" | b64enc }}
  # EBS snapshot credentials (if using backups)
  AWS_SNAPSHOT_ID: {{ .Values.secrets.ebs.snapshotId | default "" | b64enc }}