apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-redis-secrets
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  # Redis password (optional)
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc | default (randAlphaNum 16 | b64enc) }}
  # EBS encryption key (if using custom KMS)
  EBS_ENCRYPTION_KEY: {{ .Values.secrets.ebs.kmsKeyId | default "" | b64enc }}