apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.fullname" . }}-trivy-secrets
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  TRIVY_SECRET: {{ .Values.secrets.trivy.secretKey | b64enc | default (randAlphaNum 32 | b64enc) }}
  # GitHub token for vulnerability DB updates
  GITHUB_TOKEN: {{ .Values.secrets.trivy.githubToken | default "" | b64enc }}
  # EBS volume encryption context
  EBS_ENCRYPTION_CONTEXT: {{ .Values.secrets.ebs.encryptionContext | default "{}" | b64enc }}