apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harbor.fullname" . }}-jobservice-config
  labels:
    {{- include "harbor.labels" . | nindent 4 }}
data:
  config.yml: |
    # JobService Configuration
    logging:
      level: {{ .Values.jobservice.logLevel | default "info" }}
      outputs:
        - file:
            path: /var/log/jobs/jobservice.log
    
    worker_pool:
      workers: {{ .Values.jobservice.workerCount | default 10 }}
    
    storage:
      type: ebs
      ebs:
        storageClass: ebs-sc
        volumeHandle: $(EB_VOLUME_HANDLE)